### ISSUE TITLE
[FEATURE REQUEST/BUG] Quality of Life Improvements, Among Other Things

### ISSUE THREAD

**Issue by MegaShinySnivy** [kevansevans/Project-GHAG#1]
This one is a doozy of bugs and requests, so please bear with me.

1.) Make it so rage grants more effects. I'd love to see voice lines, faster movement, minor passive effects*, and maybe even a kill system similar to the one in Project Brutality, in where if you're at Murderous or HELL HATH NO FURY!!!! you have the ability to enter glory kills with your shotgun melee attack.

*things such as the screen turning redder and redder, enemies such as the zombies and imp growing afraid of you, maybe even a small aoe pushback around the player

2.) Speaking of the shotgun melee, two things. One, it currently does not make enemies drop Rage, and two, it feels very weak even at full rage. I think it's due to the swing time not increasing along with the relatively weak-sounding noise it makes. 

3.) I mentioned voice lines above, but some voice lines other than the defaults would be nice. Hideous Destructor has some excellent ones for free use.

FInally, I would love to see where you want to take this mod in terms of compatibility with other mods.

**Comment by kevansevans** [comment]
I'll investigate the shotgun melee.

Appreciate the feedback, but I can't make promises on anything, and quite frankly, I'm not interested in imitating something like PB.

**Comment by MegaShinySnivy** [comment]
Understandable, it's just the first thing that came to my head when I think of pure rage, along with your profile picture. Out of curiosity for future feedback (that way I don't give useless information), how far are you willing to go for mod cross-compatibility? 

Also in regards to voice lines, I would also be willing to provide. That, or even a text window will work. Just something to give this character as little... Character

**Comment by kevansevans** [comment]
I have zero intentions on adding specific/deliberate compatibility support towards any other mods.

**Comment by MegaShinySnivy** [comment]
I was more talking in terms of removing it, as stuff like custom monsters tends to cause issues

**Comment by kevansevans** [comment]
Behavior reported fixed here: https://github.com/kevansevans/Project-GHAG/commit/3fb0a442285699a0aa7528aa132f21d2b11da9a7

Closing report.
